### ISSUE TITLE
Error: require(...).parseDir is not a function [fixed]

### ISSUE THREAD

**Issue by Rob--W** [StudioLabs/browserify-unpack#1]
This tool doesn't work at all...

Input:

```
$ npm install -g browserify-unpack
$ browserifyunpack descendents . file.js
```

Output:

> Error: require(...).parseDir is not a function

Expected output: the current directory filled with a file for every module in file.js

**Comment by SteedMonteiro** [comment]
sorry command line wasn't supported but i fixed it. Try it and let me know.

**Comment by Rob--W** [comment]
Thanks for looking into this report! I tried again and it does not generate any output files. I get "Error: file.id.replace is not a function" with the latest version (0.2.6) of your tool.

I'm now using https://github.com/Rob--W/unpackjs to get what I wanted. It has no fancy progress bars like yours, but at least it generates the desired output files.
