### ISSUE TITLE
Windows and Module Ids as Numeric Indices Issues

### ISSUE THREAD

**Issue by TeamworkGuy2** [StudioLabs/browserify-unpack#2]
I've run into a few issues using browserify-unpack on Windows, some issues related to forward vs. backslash in paths and an error caused by the browserify/prelude.js style {"./Base64":1,"./ZipEntries":22} dependency definitions being parsed as numbers (correctly) but browserify-unpack not supporting numeric module IDs. 

I'm working through the issues now and was wondering if you're open to me sending a PR with my changes so others can benefit from them?

**Comment by SteedMonteiro** [comment]
Sorry i was busy, but of course you can send a PR. I don't use windows so if you can improve the compatibility, it's great ;)

**Comment by SteedMonteiro** [comment]
I saw what you have done, it's looking great thanks. Feel free to make a PR, i will review it ASAP.

**Comment by TeamworkGuy2** [comment]
Wow, I completely forgot about this.  Yeah, it's to help get this package working on Windows 7, I'll send a PR in a day or two, been a while since I was working on browserify stuff.

**Comment by SteedMonteiro** [comment]
ok thanks :)
