### ISSUE TITLE
Error: Cannot read property 'toObject' of null

### ISSUE THREAD

**Issue by septs** [StudioLabs/browserify-unpack#3]
```
septs@septs ~/Desktop $ node_modules/.bin/browserifyunpack -v -f live-room.bundle.min.js                               
Reading file...
Reading source map...
Error: Cannot read property 'toObject' of null
```

**Comment by dmitriyshashkin** [comment]
I've got the same problem

**Comment by SteedMonteiro** [comment]
can you send me your file ?

**Comment by SteedMonteiro** [comment]
does your file have a sourcemap inline with absolute path ?

**Comment by septs** [comment]
see http://static.hdslb.com/live-static/live-room/live-room.bundle.min.js
see http://static.hdslb.com/live-static/live-room/live-room.bundle.min.js.map

**Comment by TeamworkGuy2** [comment]
I was running into the same issue and fixed it in pull request https://github.com/StudioLabs/browserify-unpack/pull/4.

**Comment by SteedMonteiro** [comment]
The pull request is merged. I created a quick fix too.
I recommend you to use source map with absolute path to get the best of this module.
